kolomiets_home_work9:
    resource: "@KolomietsHomeWork9Bundle/Resources/config/routing.yml"
    prefix:   /

kolomiets_test_doctrine:
    resource: "@KolomietsTestDoctrineBundle/Resources/config/routing.yml"
    prefix:   /test
